{"uuid": "94560e4d-c716-48ef-99ba-5d8d9ad91015", "children": ["bcbfd7f0-9a40-4ea1-a291-eae054d26759"], "befores": [{"name": "home", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Invalid session id\n\n", "trace": "  File \"/home/headspin/.local/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/headspin/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/headspin/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/headspin/Documents/maps/io/headspin/maps/conftest.py\", line 116, in home\n    home_page = HomePage.instance(driver, request.cls)\n  File \"/home/headspin/Documents/maps/io/headspin/maps/pages/base_page.py\", line 114, in instance\n    return class_for_name('pages', klass)(driver, session_data)\n  File \"/home/headspin/Documents/maps/io/headspin/maps/pages/home_page.py\", line 94, in __init__\n    super().__init__(driver, session_data)\n  File \"/home/headspin/Documents/maps/io/headspin/maps/pages/home_page.py\", line 13, in __init__\n    super().__init__(driver, session_data)\n  File \"/home/headspin/Documents/maps/io/headspin/maps/pages/base_page.py\", line 30, in __init__\n    screen_size = self.driver.get_window_size()\n  File \"/home/headspin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 1396, in get_window_size\n    size = self.get_window_rect()\n  File \"/home/headspin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 1446, in get_window_rect\n    return self.execute(Command.GET_WINDOW_RECT)['value']\n  File \"/home/headspin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"/home/headspin/.local/lib/python3.8/site-packages/appium/webdriver/errorhandler.py\", line 31, in check_response\n    raise wde\n  File \"/home/headspin/.local/lib/python3.8/site-packages/appium/webdriver/errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"/home/headspin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1644222715631, "stop": 1644222715960}], "start": 1644222715631, "stop": 1644222716077}