{"uuid": "78eb5685-117e-47c8-8d69-211fe73915b3", "children": ["d7e1367b-0184-400b-82aa-fff3ca9662d1"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: No available good condition devices matched with your udid or HeadSpin selector in your device pool. Please make sure your device pool has online devices. \"headspin:newCommandTimeout\" or \"headspin:waitForDeviceOnlineTimeout\" capability helps to extend the waiting timeout.\nStacktrace:\n{\"capabilities\": {\"alwaysMatch\": {\"appium:newCommandTimeout\": 320, \"appium:autoAcceptAlerts\": true, \"platformName\": \"Android\", \"headspin:selector\": \"country:selector2\", \"headspin:deviceStrategy\": \"random\", \"headspin:waitForDeviceOnlineTimeout\": 5900, \"headspin:ignoreFailedDevices\": false, \"appium:appPackage\": \"com.google.android.apps.maps\", \"appium:appActivity\": \"com.google.android.maps.MapsActivity\", \"appium:disableWindowAnimation\": true, \"appium:unlockType\": \"pin\", \"appium:unlockKey\": \"1234\", \"appium:automationName\": \"UiAutomator2\", \"appium:autoGrantPermissions\": true, \"appium:autoLaunch\": false, \"appium:language\": \"en\", \"appium:locale\": \"US\", \"headspin:controlLock\": false, \"headspin:capture.video\": true, \"headspin:capture.network\": false}, \"firstMatch\": [{}]}, \"desiredCapabilities\": {\"newCommandTimeout\": 320, \"autoAcceptAlerts\": true, \"platformName\": \"Android\", \"headspin:selector\": \"country:selector2\", \"headspin:deviceStrategy\": \"random\", \"headspin:waitForDeviceOnlineTimeout\": 5900, \"headspin:ignoreFailedDevices\": false, \"appPackage\": \"com.google.android.apps.maps\", \"appActivity\": \"com.google.android.maps.MapsActivity\", \"disableWindowAnimation\": true, \"unlockType\": \"pin\", \"unlockKey\": \"1234\", \"automationName\": \"UiAutomator2\", \"autoGrantPermissions\": true, \"autoLaunch\": false, \"language\": \"en\", \"locale\": \"US\", \"headspin:controlLock\": false, \"headspin:capture.video\": true, \"headspin:capture.network\": false}}\n", "trace": "  File \"/home/headspin/.local/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/headspin/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/headspin/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/headspin/Documents/maps/io/headspin/maps/conftest.py\", line 44, in driver\n    driver = webdriver.Remote(\n  File \"/home/headspin/.local/lib/python3.8/site-packages/appium/webdriver/webdriver.py\", line 273, in __init__\n    super().__init__(\n  File \"/home/headspin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 268, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/headspin/.local/lib/python3.8/site-packages/appium/webdriver/webdriver.py\", line 364, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"/home/headspin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"/home/headspin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1644219379514, "stop": 1644219380898}], "start": 1644219379514, "stop": 1644219381094}